### ISSUE TITLE
老哥写的不错,加油

### ISSUE THREAD

**Issue by Maicarons2022** [SaminZou/study-prj#2]
前辈大佬好!
![image](https://user-images.githubusercontent.com/101958587/210041994-cb840af3-05fa-4a05-ae2e-aaa8f1c4ee0b.png)

我在v2看见您的,虽然不是java出身,但阻止不了我点star!  
已经分享给我的Java一家人了,让他们都来点!  
老哥血气方刚,还能再奋斗100年,加油老哥!

**Comment by SaminZou** [comment]
感谢支持 共勉
